### ISSUE TITLE
operatorhub: operatorgroup.create docs slightly miss-leading 

### ISSUE THREAD

**Issue by garethahealy** [rht-labs/helm-charts#23]
operatorhub chart supports: operatorgroup.create in the docs;
- https://github.com/rht-labs/helm-charts/tree/master/charts/operatorhub#configuration

Since the example is true, it's inferred that the below should not create the operator group:
```
operatorgroup:
        create: false
```

But the code just checks for the existence of the 'operatorgroup', so it doesn't matter what create is set to.
- https://github.com/rht-labs/helm-charts/blob/master/charts/operatorhub/templates/operatorgroup.yaml#L3

the wording of the docs just needs tweaking to make this clear.

CC @springdo @ckavili

**Comment by mabulgu** [comment]
Hi all,

Gareth you are right about the slightly misleading issue, I did not notice that even if I run the template. However, should it be like in the docs that will be changed in the helm template, or the docs should say "whether it is create, delete, foo, bar it will check the existence".  

The options are:

1.  The values.yaml should be changed regarding defining the right terminology:

`operatorgroup: ""` or sth like this

2.  Helm template(s) should be changed and check the operatorgroup.create false/true condition not the operatorgroup obj itself.

3.  Docs should be changed as I mentioned above.

IMHO, the elegant way is to choose whether 1 or 2.
