### ISSUE TITLE
argocd using cop image

### ISSUE THREAD

**Issue by garethahealy** [rht-labs/helm-charts#41]
Any reason to use the CoP image?
- https://github.com/rht-labs/helm-charts/blob/master/charts/argocd-operator/templates/ArgoCD.yaml#L14

cant the chart just use dex v2.22.0?

CC @eformat @springdo

**Comment by eformat** [comment]
thanks @garethahealy  - yeah for sometime this integration was broken

i have tested now with 1.5.4 of argocd and LGTM, see linked PR

i think there are still some issues with the upstream openshift connector and dex, but they are minor

https://github.com/dexidp/dex/pull/1694 
https://github.com/argoproj/argo-cd/pull/3468/files
